# Generated by Django 5.0.4 on 2024-04-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Companyname', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
